// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzthbordptyprfdwsupj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6dGhib3JkcHR5cHJmZHdzdXBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyODI2OTQsImV4cCI6MjA1MTg1ODY5NH0.e98XcJhXiJMMgbdOnshv7oORZqipLf1C6bnrOeqUIlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);